services:
  KYT_db:
    image: postgres:15
    environment:
      POSTGRES_DB: knowYourTeacher_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432
    volumes:
      - "./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./sql/data.sql:/docker-entrypoint-initdb.d/2.sql"

  know_your_teacher_app:
    image: know_your_teacher_app
    build: .
    ports:
      - 8082:8082
    depends_on:
      - KYT_db